plugins {
	id("net.twisterrob.inventory.android.module")
}

dependencies {
	implementation(libs.androidx.annotation)
	implementation(libs.androidx.loader)
	implementation("net.twisterrob.lib:twister-lib-general")
}

// See net.twisterrob.inventory.android.content.InventoryContract.AUTHORITY.
android.buildFeatures.buildConfig = true

tasks.withType(JavaCompile).configureEach {
	// Generated BuildConfig.java starts with `/** */ package` which is invalid.
	options.compilerArgs.add("-Xlint:-dangling-doc-comments")
}
