[versions]
#java = "1.8"
#
agp = "4.1.3"
## https://github.com/TWiStErRob/net.twisterrob.gradle/releases
twisterrob = "0.15"
detekt = "1.22.0"

test-junit4 = "4.13.1"

[libraries]
android-gradle = { module = "com.android.tools.build:gradle", version.ref = "agp" }
twisterrob-quality = { module = "net.twisterrob.gradle:twister-quality", version.ref = "twisterrob" }
twisterrob-android = { module = "net.twisterrob.gradle:twister-convention-plugins", version.ref = "twisterrob" }

test-junit4 = { module = "junit:junit", version.ref = "test-junit4" }

[bundles]

[plugins]
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
