[versions]
#java = "1.8"
#
agp = "7.4.2"
# 23.0.0 + agp
agp-tools = "30.4.2"
## https://github.com/TWiStErRob/net.twisterrob.gradle/releases
twisterrob = "0.15"
detekt = "1.22.0"

test-junit4 = "4.13.1"

[libraries]
plugin-android-gradle = { module = "com.android.tools.build:gradle", version.ref = "agp" }
plugin-android-tools-common = { module = "com.android.tools:common", version.ref = "agp-tools" }
plugin-android-tools-sdkCommon = { module = "com.android.tools:sdk-common", version.ref = "agp-tools" }
plugin-android-tools-ddmlib = { module = "com.android.tools.ddms:ddmlib", version.ref = "agp-tools" }
plugin-android-tools-testApi = { module = "com.android.tools.build:builder-test-api", version.ref = "agp" }
plugin-twisterrob-quality = { module = "net.twisterrob.gradle:twister-quality", version.ref = "twisterrob" }
plugin-twisterrob-android = { module = "net.twisterrob.gradle:twister-convention-plugins", version.ref = "twisterrob" }

test-junit4 = { module = "junit:junit", version.ref = "test-junit4" }

[bundles]

[plugins]
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
