BEGIN TRANSACTION;

DROP TABLE IF EXISTS Room;
DROP TABLE IF EXISTS RoomType;
DROP TABLE IF EXISTS RoomTypeKind;
DROP TABLE IF EXISTS Property;
DROP TABLE IF EXISTS PropertyType;
DROP TABLE IF EXISTS Category;

END TRANSACTION;

