BEGIN TRANSACTION;

DROP TABLE IF EXISTS Room;
DROP TABLE IF EXISTS RoomType;
DROP TABLE IF EXISTS RoomTypeKind;
DROP TABLE IF EXISTS Property;
DROP TABLE IF EXISTS PropertyType;
DROP TABLE IF EXISTS Item;
DROP TABLE IF EXISTS Category_Descendant;
DROP TABLE IF EXISTS Category;
DROP TABLE IF EXISTS Path;
DROP TABLE IF EXISTS Paths;

END TRANSACTION;

