BEGIN TRANSACTION;

DROP TABLE IF EXISTS Room;
DROP TABLE IF EXISTS RoomType;
DROP TABLE IF EXISTS RoomTypeKind;
DROP TABLE IF EXISTS Building;
DROP TABLE IF EXISTS BuildingType;
DROP TABLE IF EXISTS Category;

END TRANSACTION;

