BEGIN TRANSACTION;

DROP TABLE IF EXISTS Room;
DROP TABLE IF EXISTS RoomType;
DROP TABLE IF EXISTS RoomTypeKind;

DROP TABLE IF EXISTS Property;
DROP TABLE IF EXISTS PropertyType;

DROP VIEW IF EXISTS Item_Paths;
DROP TABLE IF EXISTS Item_Path;
DROP TABLE IF EXISTS Item;

DROP TABLE IF EXISTS Category_Descendant;
DROP TABLE IF EXISTS Category;

DROP TABLE IF EXISTS Log;
DROP TABLE IF EXISTS Search;

END TRANSACTION;

