BEGIN TRANSACTION;

DROP VIEW IF EXISTS Room_Rooter;
DROP TABLE IF EXISTS Room;
DROP TABLE IF EXISTS RoomType;
DROP TABLE IF EXISTS RoomTypeKind;

DROP TABLE IF EXISTS Property;
DROP TABLE IF EXISTS PropertyType;

DROP VIEW IF EXISTS Item_Path;
DROP VIEW IF EXISTS Item_Path_Node_Name;
DROP TABLE IF EXISTS Item_Path_Node;
DROP TABLE IF EXISTS Item;

DROP TABLE IF EXISTS Category_Descendant;
DROP TABLE IF EXISTS Category;
DROP TABLE IF EXISTS Category_Name_Cache;

DROP VIEW IF EXISTS Search_View;
DROP TABLE IF EXISTS Search;

DROP TABLE IF EXISTS Log;

END TRANSACTION;

