name: "🎨 Icons"

on:
  workflow_call

jobs:

  previews:
    name: "🪟 Generate Previews"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    permissions:
      # actions/checkout
      contents: read

    steps:

      - name: "Checkout ${{ github.ref }} branch in ${{ github.repository }} repository."
        uses: actions/checkout@v4

      - name: "Generate icon previews."
        working-directory: android/data/src/main/res/raw
        run: node icon_preview.js > icon_previews.html

      - name: "Upload 'Icon Previews' artifact."
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: 'Icon Previews'
          path: |
            ${{ github.workspace }}/android/data/src/main/res/raw/icon_previews.html
            ${{ github.workspace }}/android/data/src/main/res/raw/*.svg


  nu-validator:
    name: "🕵 Validate SVGs"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    permissions:
      # actions/checkout
      contents: read

    steps:

      - name: "Checkout ${{ github.ref }} branch in ${{ github.repository }} repository."
        uses: actions/checkout@v4

      - name: Register problem matchers.
        run: echo "::add-matcher::.github/problemMatchers-icons.json"

      - name: "Validate with W3C Nu Validator"
        env:
          VNU_VERSION: 20.6.30
        run: |
          curl --silent --show-error --location --remote-name \
             https://github.com/validator/validator/releases/download/${VNU_VERSION?}/vnu.jar_${VNU_VERSION?}.zip
          unzip "vnu.jar_*.zip"
          java -jar ./dist/vnu.jar --version
          java -jar ./dist/vnu.jar \
             --asciiquotes \
             --Werror \
             --verbose \
             --svg \
             android/data/src/main/res/raw/*.svg \
