name: "CI"

on:
  push:
    branches:
      - '**'

concurrency:
  group: ${{ github.ref == 'refs/heads/main' && format('ci-main-{0}', github.sha) || format('ci-{0}', github.ref) }}
  cancel-in-progress: true

jobs:

  validate:
    name: "🦺 Validation"
    uses: TWiStErRob/github-workflows/.github/workflows/validate.yml@104620e2c495f0c905fde6f15ea2b6453ae4eaed # v3
    permissions:
      contents: read
      security-events: write
      actions: read

  build:
    name: "🔨 Build & Verify"
    needs: validate
    uses: ./.github/workflows/ci-build.yml
    permissions:
      contents: read
      checks: write
      security-events: write

  icons:
    name: "🎨 Icons"
    uses: ./.github/workflows/ci-icons.yml
    permissions:
      contents: read

  instrumentation:
    name: "🧪 Instrumentation Tests on" # / API ${{ matrix.api }} will be appended by used workflow.
    needs: validate
    uses: ./.github/workflows/ci-instrumentation.yml
    permissions:
      contents: read
      checks: write
      statuses: write
